### ISSUE TITLE
client code refactor openpype calls

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/ayon-aquarium#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Client code doesn't work because of openpype calls.
```
Traceback (most recent call last):
  File "E:\Ynput\ayon-core\client\ayon_core\addon\base.py", line 363, in _load_ayon_addons
    mod = __import__(basename, fromlist=("",))
  File "E:\Ynput\ayon-aquarium\client\ayon_aquarium\__init__.py", line 2, in <module>
    from .addon import AquariumAddon
  File "E:\Ynput\ayon-aquarium\client\ayon_aquarium\addon.py", line 5, in <module>
    from openpype.modules import (
ModuleNotFoundERROR: No module named 'openpype'
```

### Expected Behavior:

openpype calls should be refactored to ayon calls.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. install the addon
2. add it to your bundle
3. run ayon launcher

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by ymoriaud** [comment]
Thanks. Do you have any example or document on the correct import that need to be used ?

**Comment by BigRoy** [comment]
It would be from `ayon_core` most likely.

Some of this may help:
- https://gist.github.com/BigRoy/909d1178447f945cb482e3f571c97eaa
- https://community.ynput.io/t/openpype-to-ayon-core-addon-conversion/1209
